package com.iblu01.portallauncher

/** Loads real web files so the UI can also be opened directly in a browser. */
internal object WebConfigPage {
    fun render(token: String, language: String = "fr"): String = localized(resource("config.html"), language)
        .replace("%TOKEN%", token)

    fun renderAccess(invalidCode: Boolean, language: String = "fr"): String = localized(resource("access.html"), language)
        .replace("%INVALID_CODE%", invalidCode.toString())

    fun asset(name: String, language: String = "fr"): String = localized(resource(name), language)

    private fun localized(source: String, language: String): String {
        val prepared = source.replace("%LANG%", language)
        if (language != "en") return prepared
        return english.entries.fold(prepared.replace("lang=\"fr\"", "lang=\"en\"")) { text, (french, english) ->
            text.replace(french, english)
        }
    }

    /** French remains the source layout; this table also covers every message emitted by its JS. */
    private val english = linkedMapOf(
        "Le panneau n’a pas confirmé l’affichage. Les réglages n’ont pas été enregistrés." to "The panel did not confirm the display. Settings were not saved.",
        "Cet aperçu n’est plus la version affichée sur le panneau. Rechargez les valeurs." to "This preview is no longer the version displayed on the panel. Reload the settings.",
        "Jeton Home Assistant requis. Saisissez un jeton longue durée ou ignorez ce provider." to "Home Assistant token required. Enter a long-lived token or skip this provider.",
        "Utilisateur MQTT requis quand un mot de passe est fourni." to "MQTT username required when a password is provided.",
        "Port MQTT invalide. Saisissez un entier entre 1 et 65535." to "Invalid MQTT port. Enter an integer between 1 and 65535.",
        "Identifiants déjà configurés. Laissez le mot de passe vide pour le conserver." to "Credentials already configured. Leave the password empty to keep it.",
        "8 caractères, sans espaces." to "8 characters, no spaces.",
        "Cette session utilise HTTP sur le réseau local. N’utilisez pas un Wi-Fi public ou partagé." to "This session uses HTTP on the local network. Do not use public or shared Wi-Fi.",
        "Réseau local de confiance requis" to "Trusted local network required",
        "Aperçu disponible sur le panneau" to "Preview available on the panel",
        "La configuration de cette source sera disponible au Lot 3." to "This source will be configurable in Lot 3.",
        "Disponible au Lot 3" to "Available in Lot 3",
        "Aucun provider n’est configuré. Portal restera utilisable et pourra être réglé plus tard." to "No provider is configured. Portal will remain usable and can be configured later.",
        "Aucun provider sélectionné. Portal utilisera uniquement les fonctions locales." to "No provider selected. Portal will use local functions only.",
        "La configuration de cette source est disponible dans l’étape provider correspondante." to "Configure this source in its provider step.",
        "Recommencer l’onboarding ? Les réglages actuels seront conservés." to "Restart onboarding? Current settings will be kept.",
        "Chaque provider est indépendant. Home Assistant n’active pas MQTT." to "Each provider is independent. Home Assistant does not enable MQTT.",
        "Mot de passe déjà configuré. Laissez le champ vide pour le conserver." to "Password already configured. Leave this field empty to keep it.",
        "Jeton déjà configuré. Laissez le champ vide pour le conserver." to "Token already configured. Leave this field empty to keep it.",
        "Clé déjà configurée. Laissez le champ vide pour la conserver." to "Key already configured. Leave this field empty to keep it.",
        "Le panneau ouvre Portal. Cet onglet peut être fermé." to "The panel is opening Portal. You can close this tab.",
        "Un autre navigateur modifie cet appareil." to "Another browser is editing this device.",
        "L’échec de Gemini ne bloque pas l’activation de Portal." to "A Gemini failure does not block Portal activation.",
        "Session en lecture seule" to "Read-only session",
        "Reprendre la main" to "Take over editing",
        "Utiliser les valeurs par défaut" to "Use default values",
        "Action requise" to "Action required",
        "Ignoré" to "Skipped",
        "Prêt" to "Ready",
        "Modifier" to "Edit",
        "Connexion Internet requise" to "Internet connection required",
        "Entités, commandes et caméras" to "Entities, commands and cameras",
        "Contrôle distant du panneau" to "Remote panel control",
        "Taille des icônes" to "Icon size",
        "Applications visibles" to "Visible applications",
        "Colonnes simulées" to "Simulated columns",
        "Annuler l’aperçu" to "Revert preview",
        "Assombrissement" to "Dimming",
        "Interruption vocale" to "Voice interruption",
        "Ignorer Home Assistant" to "Skip Home Assistant",
        "Ignorer MQTT" to "Skip MQTT",
        "Ignorer Gemini" to "Skip Gemini",
        "Activer Portal" to "Activate Portal",
        "Onboarding terminé" to "Onboarding complete",
        "Panneau hors ligne" to "Panel offline",
        "Commande refusée" to "Command rejected",
        "Aucun provider n’est configuré" to "No provider is configured",
        "Finalisation" to "Finish",
        "Vérification" to "Review",
        "Providers" to "Providers",
        "Précédent" to "Back",
        "Continuer" to "Continue",
        "Recharger" to "Reload",
        "Recommencer" to "Restart",
        "Facultatif" to "Optional",
        "En attente" to "Waiting",
        "Synchronisée" to "Synchronized",
        "Révision" to "Revision",
        "Aperçu" to "Preview",
        "Recommencer l’onboarding ? Vos réglages actuels seront conservés." to "Restart onboarding? Your current settings will be kept.",
        "Gardez cette page ouverte et vérifiez que les deux appareils utilisent le même réseau." to "Keep this page open and check that both devices are on the same network.",
        "Vos choix sont enregistrés sur le panneau au fil de la configuration." to "Your choices are saved on the panel as you go.",
        "Ajoutez votre adresse et votre jeton, ou passez cette étape pour le moment." to "Add your address and token, or skip this step for now.",
        "Connectez votre broker MQTT. Cette intégration reste facultative." to "Connect your MQTT broker. This integration remains optional.",
        "Choisissez une densité et un fond adaptés à la pièce." to "Choose a density and background suited to the room.",
        "Le panneau ouvre maintenant le launcher. Vous pouvez fermer cet onglet." to "The panel is now opening the launcher. You can close this tab.",
        "J’ai compris les gestes de navigation de Portal." to "I understand Portal's navigation gestures.",
        "Si l’adresse en .local échoue, utilisez l’adresse IP locale du serveur." to "If the .local address fails, use the server's local IP address.",
        "Si l’adresse en .local échoue, utilisez son adresse IP locale." to "If the .local address fails, use its local IP address.",
        "MQTT est facultatif. Il permet de piloter le panneau à distance." to "MQTT is optional. It lets you control the panel remotely.",
        "Configurer Home Assistant plus tard" to "Set up Home Assistant later",
        "Configurer MQTT plus tard" to "Set up MQTT later",
        "Recommencer l’onboarding" to "Restart onboarding",
        "Connexion au panneau interrompue" to "Connection to the panel was interrupted",
        "Pilotez le panneau à distance" to "Control the panel remotely",
        "Vérifiez, puis lancez Portal" to "Review, then launch Portal",
        "Connectez votre maison" to "Connect your home",
        "Adaptez l’affichage" to "Adjust the display",
        "Configuration de Portal" to "Portal setup",
        "Configuration du panneau" to "Panel configuration",
        "Taille des éléments" to "Element size",
        "Plus d’apps visibles" to "More apps visible",
        "Lecture à distance" to "Readable from a distance",
        "Fond Android actuel" to "Current Android background",
        "Discret et toujours lisible" to "Quiet and always readable",
        "Assombrissement" to "Dimming",
        "Dernière étape" to "Last step",
        "Lancer Portal" to "Launch Portal",
        "Portal est prêt" to "Portal is ready",
        "Panneau connecté" to "Panel connected",
        "Étape " to "Step ",
        "Affichage" to "Display",
        "Finalisation" to "Finish",
        "Équilibré" to "Balanced",
        "Recommandé" to "Recommended",
        "Confort" to "Comfort",
        "Compact" to "Compact",
        "Plus tard" to "Later",
        "Fond" to "Background",
        "Neutre" to "Neutral",
        "Système" to "System",
        "Le panneau" to "The panel",
        "Les adresses en <strong>.local</strong> utilisent le DNS local (mDNS), qui peut ne pas fonctionner sur certains écrans. Si la connexion échoue, utilisez plutôt l’adresse IP locale du serveur." to "Addresses ending in <strong>.local</strong> use local DNS (mDNS), which may not work on some panels. If the connection fails, use the server's local IP address instead.",
        "Rouvrez « Configurer depuis un autre appareil » sur le panneau, puis scannez le nouveau QR code." to "Open “Configure from another device” again on the panel, then scan the new QR code.",
        "Home Assistant refuse ce jeton. Vérifiez qu’il s’agit d’un jeton longue durée valide." to "Home Assistant rejected this token. Check that it is a valid long-lived access token.",
        "Serveur MQTT introuvable. Si son adresse se termine par .local, essayez son adresse IP locale." to "MQTT server not found. If its address ends in .local, try its local IP address.",
        "Adresse introuvable. Si elle se termine par .local, essayez l’adresse IP locale." to "Address not found. If it ends in .local, try the local IP address.",
        "La connexion MQTT a été refusée. Vérifiez l’identifiant et le mot de passe." to "The MQTT connection was rejected. Check the username and password.",
        "Les identifiants MQTT sont distincts de ceux de Home Assistant." to "MQTT credentials are separate from Home Assistant credentials.",
        "Les tests ont réussi, mais l’enregistrement a échoué." to "The tests passed, but the settings could not be saved.",
        "Indiquez l’adresse de votre maison et son jeton d’accès." to "Enter your home's address and its access token.",
        "Ajoutez le serveur utilisé pour piloter le panneau à distance." to "Add the server used to control the panel remotely.",
        "Tout est prêt. Confirmez pour appliquer les modifications." to "Everything is ready. Confirm to apply the changes.",
        "Adresse trouvée, mais le port Home Assistant est inaccessible." to "Address found, but the Home Assistant port is unreachable.",
        "Le serveur répond, mais l’API Home Assistant est inaccessible." to "The server responded, but the Home Assistant API is unreachable.",
        "Serveur trouvé, mais le port MQTT est inaccessible." to "Server found, but the MQTT port is unreachable.",
        "Saisissez une adresse commençant par http:// ou https://." to "Enter an address beginning with http:// or https://.",
        "Renseignez un serveur et un port compris entre 1 et 65535." to "Enter a server and a port between 1 and 65535.",
        "Le téléphone et le panneau doivent utiliser le même réseau Wi-Fi." to "The phone and panel must use the same Wi-Fi network.",
        "Le launcher n’est pas en mode configuration" to "The launcher is not in configuration mode",
        "Le panneau a bien reçu les nouveaux réglages." to "The panel received the new settings.",
        "Code incorrect. Consultez le panneau pour le vérifier." to "Incorrect code. Check the code shown on the panel.",
        "Saisissez le code affiché sur le panneau." to "Enter the code shown on the panel.",
        "Configuration à distance" to "Remote configuration",
        "Configuration enregistrée" to "Configuration saved",
        "Vous pouvez fermer cet onglet." to "You can close this tab.",
        "Connectez Home Assistant" to "Connect Home Assistant",
        "Vérifiez la configuration" to "Review the configuration",
        "Configurez MQTT" to "Configure MQTT",
        "Le jeton d’accès est nécessaire." to "The access token is required.",
        "Le test de connexion a échoué." to "The connection test failed.",
        "Le test MQTT a échoué." to "The MQTT test failed.",
        // Voice assistant (Gemini Live). Longest strings first: the map is applied in order, so a
        // short French phrase that is a substring of a longer one must never be replaced first.
        "Sans annulation d’écho, le micro entend le haut-parleur et l’assistant s’interrompt en boucle : laissez cette option désactivée si le panneau se coupe tout seul." to
            "Without echo cancellation the microphone hears the loudspeaker and the assistant cuts itself off in a loop: leave this off if the panel interrupts itself.",
        "Collez votre clé Google AI Studio. Le panneau parlera à Gemini en direct et pilotera votre maison." to
            "Paste your Google AI Studio key. The panel will talk to Gemini live and control your home.",
        "Configurer l’assistant vocal plus tard" to "Set up the voice assistant later",
        "Autoriser à couper l’assistant" to "Allow cutting the assistant off",
        "Donnez une voix au panneau" to "Give the panel a voice",
        "La clé API est nécessaire." to "The API key is required.",
        "Clé API Gemini" to "Gemini API key",
        "Clé Google AI Studio" to "Google AI Studio key",
        "Afficher la clé" to "Show key",
        "Masquer la clé" to "Hide key",
        "Modèle Live" to "Live model",
        "Assistant vocal" to "Voice assistant",
        "Voix" to "Voice",
        // Test failures (config.js `failures`). Longest first: the map substitutes in order.
        "Ce modèle n’existe pas. Videz le champ pour reprendre le modèle par défaut." to
            "This model does not exist. Clear the field to fall back to the default model.",
        "Ce modèle ne fait pas de voix à voix. Prenez un modèle « native audio »." to
            "This model does not do speech-to-speech. Pick a \"native audio\" model.",
        "Le panneau n’a pas joint Google. Vérifiez sa connexion internet." to
            "The panel could not reach Google. Check its internet connection.",
        "Clé refusée par Google. Vérifiez la clé AI Studio." to
            "Key refused by Google. Check the AI Studio key.",
        "Home Assistant a répondu, mais pas son API." to "Home Assistant answered, but its API did not.",
        "Identifiants refusés par le broker." to "Credentials refused by the broker.",
        "Jeton refusé par Home Assistant." to "Token refused by Home Assistant.",
        "Adresse introuvable sur ce réseau." to "Address not found on this network.",
        "Port fermé ou serveur éteint." to "Port closed or server switched off.",
        "Port fermé ou broker éteint." to "Port closed or broker switched off.",
        "Clé API" to "API key",
        "Échec" to "Failed",
        "Jeton longue durée" to "Long-lived access token",
        "Jeton Home Assistant" to "Home Assistant token",
        "Nom du panneau" to "Panel name",
        "Panneau salon" to "Living room panel",
        "Mot de passe" to "Password",
        "Utilisateur" to "Username",
        "Authentification" to "Authentication",
        "Afficher le jeton" to "Show token",
        "Masquer le jeton" to "Hide token",
        "Code d’accès" to "Access code",
        "Choisir la langue" to "Choose language",
        "Le code contient 8 caractères." to "The code contains 8 characters.",
        "Maison · étape 1 sur 3" to "Home · step 1 of 3",
        " · étape " to " · step ",
        " sur " to " of ",
        "Progression" to "Progress",
        "Vérification du panneau…" to "Checking the panel…",
        "Vérification…" to "Checking…",
        "Test en cours…" to "Testing…",
        "Enregistrement…" to "Saving…",
        "Connexion interrompue" to "Connection interrupted",
        "En attente" to "Waiting",
        "Enregistrer" to "Save",
        "Continuer" to "Continue",
        "Précédent" to "Back",
        "Réessayer" to "Try again",
        "Terminé" to "Done",
        "Validé" to "Passed",
        "Échec" to "Failed",
        "Vérification" to "Review",
        "Contrôle" to "Control",
        "Maison" to "Home",
        "Serveur" to "Server",
        "Adresse" to "Address",
        "Jeton" to "Token",
        "Panneau" to "Panel",
        "Port" to "Port",
    )

    private fun resource(name: String): String = requireNotNull(
        WebConfigPage::class.java.getResourceAsStream("/webconfig/$name"),
    ) { "Missing web configuration resource: $name" }
        .bufferedReader(Charsets.UTF_8)
        .use { it.readText() }
}
